### POST
POST http://localhost:7000/user
Content-Type: application/json

{
  "username": "이정섭",
  "email": "test@test4.com",
  "password": "asdf"
}

### GET
GET http://localhost:7000/user?id=1

### PATCH
PATCH http://localhost:7000/user
Content-Type: application/json

{
  "id": 1,
  "username": "나노아이티",
  "email": "nanoit@nanoit.com",
  "password": "asd"
}

### DELETE
DELETE http://localhost:7000/user?id=1